name: Destroy Preview Environment

on: [delete]

jobs:
  destroy-preview:
    name: Destroy Preview Environment

    runs-on: ubuntu-latest

    if: github.event.ref_type == 'branch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Deps
        working-directory: infra
        run: yarn install

      - name: Configure Pulumi Stack
        working-directory: infra
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        run: |
          # TODO: stack name should be branch specific to allow separate testing
          # environments per PR, but that could limit the characters we can use
          # in branch names
          pulumi stack select --create preview

          pulumi config set domain 'console.lol'

          # this is the branch name that triggered the delete event
          pulumi config set subdomain '${{ github.event.ref }}'

          # set config secrets
          pulumi config set --secret digitalocean:token '${{ secrets.DO_API_TOKEN }}'
          pulumi config set --secret database_password '${{ secrets.DATABASE_PASSWORD }}'
          pulumi config set --secret database_url '${{ secrets.DATABASE_URL }}'
          pulumi config set --secret secret_key_base '${{ secrets.SECRET_KEY_BASE }}'

      - name: Destroy Infra with Pulumi
        uses: pulumi/actions@v3
        with:
          command: destroy
          stack-name: preview
          github-token: ${{ secrets.GITHUB_TOKEN }}
          work-dir: infra
          upsert: true
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
