name: CI / CD

on:
  pull_request:
    branches: ['master']

jobs:
  docker-build:
    name: Build & Push Docker Image

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up image metadata and tags
        id: imageMeta
        uses: docker/metadata-action@v4
        with:
          images: dkarter/neptune
          tags: |
            type=sha

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.imageMeta.outputs.tags }}

  deploy:
    name: Deploy Preview

    runs-on: ubuntu-latest
    needs: [docker-build]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Deps
        working-directory: infra
        run: yarn install

      # Use branch name to create a human friendly code name.
      # This will allow using something like 'feature/something-very-long' as a
      # branch name and not have to worry about the subdomain or Pulumi stack
      # name having invalid characters, and at the same time maintain a
      # consistent reference we can use to spin down the environment when the PR
      # is merged
      - name: Generate codename
        id: codeName
        uses: reallyreallyreal/codenamize-action@v1.1.0
        with:
          # this is the branch name for the PR
          seed: '${{ github.head_ref }}'

      - name: Configure Pulumi Stack
        working-directory: infra
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        run: |
          pulumi stack select --create 'preview-${{ steps.codeName.outputs.codename }}'

          pulumi config set domain 'console.lol'
          pulumi config set subdomain '${{ steps.codeName.outputs.codename }}'
          pulumi config set git_sha '${{ github.sha }}'

          # set config secrets
          pulumi config set --secret digitalocean:token '${{ secrets.DO_API_TOKEN }}'
          pulumi config set --secret database_password '${{ secrets.DATABASE_PASSWORD }}'
          pulumi config set --secret database_url '${{ secrets.DATABASE_URL }}'
          pulumi config set --secret secret_key_base '${{ secrets.SECRET_KEY_BASE }}'

      - name: Deploy with Pulumi
        uses: pulumi/actions@v3
        with:
          command: up
          stack-name: 'preview-${{ steps.codeName.outputs.codename }}'
          comment-on-pr: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          work-dir: infra
          upsert: true
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
