name: CI / CD

on:
  # push:
  #   branches: [ "master" ]
  pull_request:
    branches: ['master']

jobs:
  docker-build:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up image metadata and tags
        id: imageMeta
        uses: docker/metadata-action@v4
        with:
          images: dkarter/neptune
          tags: |
            type=sha

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.imageMeta.outputs.tags }}
